spring:
  config:
    activate:
      on-profile: demo
name: demo-YAML
environment: demo
host: localhost
server.port: 3000
ml:
  username: admin
  password: admin
  host: localhost
  port:
    emerald: 8383
    books: 8060
    customers: 8090

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
host: localhost
server.port: 3000
ml:
  username: admin
  password: admin
  host: localhost
  port:
    emerald: 8383
    books: 8060
    customers: 8090

#logging.level.com.springboot : INFO

#to manually kill server port running :
#  netstat -nao | find "5090"